### ISSUE TITLE
react 17 is unsupported

### ISSUE THREAD

**Issue by frfancha** [davidchin/react-input-range#194]
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^15.0.0 || ^16.0.0" from react-input-range@1.3.0
npm ERR! node_modules/react-input-range
npm ERR!   react-input-range@"*" from the root project

**Comment by jjorissen52** [comment]
I doubt that React is going to make a change that breaks this library. Please consider an open-ended react dependency which matches `devDependencies.react`, or, preferably, even less restrictive than that.

**Comment by chubun** [comment]
I removed devDependencies and tried to build the package but 'npm i' gave tons of errors.  Any suggestion.

npm ERR! code 1
npm ERR! path c:\Projects\react-input-range\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: C:\Program Files\nodejs\node.exe c:\Projects\react-input-range\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   'c:\\Projects\\react-input-range\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
...
npm ERR! gyp verb "Release" dir needed to be created? null
npm ERR! gyp verb copying "node.lib" for x64 C:\Users\mytest\.node-gyp\14.15.0\Release\node.lib
npm ERR! gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\Bin\MSBuild.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'build/binding.sln',
npm ERR! gyp info spawn args   '/nologo',
npm ERR! gyp info spawn args   '/p:Configuration=Release;Platform=x64'
npm ERR! gyp info spawn args ]
npm ERR! gyp ERR! UNCAUGHT EXCEPTION
npm ERR! gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\Bin\MSBuild.exe ENOENT
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
npm ERR! gyp ERR! stack     at onErrorNT (internal/child_process.js:465:16)
npm ERR! gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:80:21)
npm ERR! gyp ERR! System Windows_NT 10.0.19041
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "c:\\Projects\\react-input-range\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd c:\Projects\react-input-range\node_modules\node-sass
npm ERR! gyp ERR! node -v v14.15.0
npm ERR! gyp ERR! node-gyp -v v3.6.0
npm ERR! gyp ERR! This is a bug in `node-gyp`.
npm ERR! gyp ERR! Try to update node-gyp and file an Issue if it does not help:
npm ERR! gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
npm ERR! Build failed with error code: 7

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mytest\AppData\Local\npm-cache\_logs\2021-07-01T00_44_08_197Z-debug.log

**Comment by NicolaG1993** [comment]
I had the same issue
`npm install react-input-range --force` solved the errors, not sure if it is the best way to do it... but at least its working now

**Comment by satya1505** [comment]
> npm install react-input-range --force

thanks

**Comment by aka47** [comment]
After updating to react 17 I get this error: 

```
Uncaught TypeError: Cannot read properties of null (reading 'ownerDocument')
    at InputRange.removeDocumentMouseUpListener (input-range.js:494)
    at InputRange.componentWillUnmount (input-range.js:216)
```

react 17 made some changes to its event system, not sure if relates to it. But strange.
