### ISSUE TITLE
Set up for development

### ISSUE THREAD

**Issue by amannn** [davidchin/react-input-range#5]
I'd like to set the project up for development, so I can send some pull requests regarding the issues I've opened, so I don't have to bother you too much :).

However, I'm having some troubles with running `npm run start` after `npm install`:

```
❯ npm run start

> react-input-range@0.2.3 start /Users/Jan/Projects/OpenSource/react-input-range
> gulp run

[11:44:34] Requiring external module babel-core/register
module.js:338
    throw err;
          ^
Error: Cannot find module '/Users/Jan/Projects/OpenSource/react-input-range/build/react-input-range'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.require.resolve (module.js:388:19)
    at Object.<anonymous> (/Users/Jan/Projects/OpenSource/react-input-range/tasks/config.js:48:15)
    at Module._compile (module.js:460:26)
    at normalLoader (/Users/Jan/Projects/OpenSource/react-input-range/node_modules/babel-core/lib/api/register/node.js:199:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/Jan/Projects/OpenSource/react-input-range/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

npm ERR! Darwin 15.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "start"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! react-input-range@0.2.3 start: `gulp run`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-input-range@0.2.3 start script 'gulp run'.
npm ERR! This is most likely a problem with the react-input-range package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp run
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-input-range
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Jan/Projects/OpenSource/react-input-range/npm-debug.log
```

Also `npm run build` brings up the same error.

And one more question: Could you be so kind to tell me how to install `scss_lint` locally in the project folder? I've installed it through `sudo gem install scss-lint`, but `npm run test` tells me that I don't have `scss_lint` installed?

Thank you very much!

**Comment by davidchin** [comment]
Try running `npm install && bundle install` before you run `npm start`. I assume you have Bundler installed. If not, just `gem install bundler` before running the aforementioned commands. :) If successful, you should be able to develop locally.

**Comment by amannn** [comment]
Works perfect now! Wasn't aware of `bundler` :)
